### Get all events
GET http://localhost:3005/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI

### Get event by id
GET http://localhost:3005/api/events/4b7aaac8-59d7-4f83-96ac-5130280ddf41
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI

### Create event
POST http://localhost:3005/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI
Content-Type: application/json

{
    "name": "Test event Test 2343245",
    "description": "Test event description",
    "eventDate": "2023-10-10T00:00:00.000Z",    
    "amountTickets": 50,
    "userId": "e38624bb-88cd-46ca-babd-dbcdea22daa8"
}


### Update event
PUT http://localhost:3005/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI
Content-Type: application/json

{
    "id": "4b7aaac8-59d7-4f83-96ac-5130280ddf41",
    "name": "Test event Test 234324",
    "description": "Test event description",
    "eventDate": "2023-10-10T00:00:00.000Z",
    "amountTickets": 50,
    "amountReservations": 0
}


### Deactive event
PATCH http://localhost:3005/api/events/deactive/4b7aaac8-59d7-4f83-96ac-5130280ddf41
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI