### Get all events
GET http://localhost:3005/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1MTRmZWZhLWQ3OWEtNDBmMy1iYjY5LWMwOTEwMzQzNjJkYyIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyMzRAb3V0bG9vay5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Mzk3OTQ5NjIsImV4cCI6MTczOTg4MTM2Mn0.fRhKbhBvv2XmrLFMvuLau0k3f5EKn34c2ccwPX65wfw

### Get event by id
GET http://localhost:3005/api/events/a38940f5-3f35-416d-9f02-736814430761
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1MTRmZWZhLWQ3OWEtNDBmMy1iYjY5LWMwOTEwMzQzNjJkYyIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyMzRAb3V0bG9vay5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Mzk3OTQ5NjIsImV4cCI6MTczOTg4MTM2Mn0.fRhKbhBvv2XmrLFMvuLau0k3f5EKn34c2ccwPX65wfw

### Create event
POST http://localhost:3005/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1MTRmZWZhLWQ3OWEtNDBmMy1iYjY5LWMwOTEwMzQzNjJkYyIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyMzRAb3V0bG9vay5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Mzk3OTQ5NjIsImV4cCI6MTczOTg4MTM2Mn0.fRhKbhBvv2XmrLFMvuLau0k3f5EKn34c2ccwPX65wfw
Content-Type: application/json

{
    "name": "Test event Test",
    "description": "Test event description",
    "eventDate": "2023-10-10T00:00:00.000Z",    
    "amountTickets": 50
}


### Update event
PUT http://localhost:3005/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1MTRmZWZhLWQ3OWEtNDBmMy1iYjY5LWMwOTEwMzQzNjJkYyIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyMzRAb3V0bG9vay5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Mzk3OTQ5NjIsImV4cCI6MTczOTg4MTM2Mn0.fRhKbhBvv2XmrLFMvuLau0k3f5EKn34c2ccwPX65wfw
Content-Type: application/json

{
    "id": "5f128fd1-7d07-44c9-a02c-924575bcdfb9",
     "name": "Test event Test",
    "description": "Test event description",
    "eventDate": "2023-10-10T00:00:00.000Z",    
    "amountTickets": 50,
    "amountReservations": 15
}


### Deactive event
PATCH http://localhost:3005/api/events/deactive/a38940f5-3f35-416d-9f02-736814430761
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1MTRmZWZhLWQ3OWEtNDBmMy1iYjY5LWMwOTEwMzQzNjJkYyIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyMzRAb3V0bG9vay5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Mzk3OTQ5NjIsImV4cCI6MTczOTg4MTM2Mn0.fRhKbhBvv2XmrLFMvuLau0k3f5EKn34c2ccwPX65wfw