### Get all reservations
GET http://localhost:3005/api/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI

### Get reservation by id
GET http://localhost:3005/api/reservations/f6b93565-fd57-40a3-ba9d-44836be80c62
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI

### Create reservation
POST http://localhost:3005/api/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI
Content-Type: application/json

{
    "userId": "6857c9c1-7ddf-458d-bcea-1e77a734caad",
    "eventPartyId": "9bca2ea2-9555-459f-8313-fafe6365a7c3",
    "amountReservations": 3
}


### Update reservation
PUT http://localhost:3005/api/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI
Content-Type: application/json

{
    "id": "f6b93565-fd57-40a3-ba9d-44836be80c62",
    "userId": "e38624bb-88cd-46ca-babd-dbcdea22daa8",
    "eventPartyId": "9bca2ea2-9555-459f-8313-fafe6365a7c3",
    "amountReservations": 14
}


### Deactive reservation
PATCH http://localhost:3005/api/reservations/deactive/9d29d371-d526-4cef-a1f0-b7f8bc9f3a7b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzgwNTBkLTBkYTMtNGIzNC04NWExLTIwZTE5YzA4MWY3MSIsIm5hbWUiOiJKaG9uYXRhbiBBemV2ZWRvMTIzMTIzMTIzIiwiZW1haWwiOiJkZXYuYXpldmVkbzEyM0BvdXRsb29rLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczOTkwMjI1NywiZXhwIjoxNzM5OTg4NjU3fQ.iyA4MjzPq8oqXUw_RO1Bvp6zUNhaZJI6_aRgmmvb_aI